version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: targetMVD

jobs:
  build:
    docker:
      - image: circleci/python:3.7.7
      - image: circleci/postgres:alpine-postgis-ram
        environment:
          POSTGRES_USER: $DB_USER
          POSTGRES_PASSWORD: $DB_PASSWORD
          POSTGRES_DB: $DB_NAME
    environment:
      SECRET_KEY: $SECRET_KEY
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
    steps:
      - checkout
      - run:
          name: Updating pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip==20.0.2
      - run:
          name: Installing GDAL
          command: |
            sudo apt-get install libgdal-dev
      - run:
          name: Installing pip requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r base/requirements/base.txt
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            coverage run --source="." manage.py test
      - run:
          name: Checking coverage
          command: |
            . venv/bin/activate
            coverage report --omit=venv/*,manage.py --fail-under=90