# Generated by Django 3.0.3 on 2020-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('detail', models.TextField(blank=True)),
            ],
        ),
    ]
