# Generated by Django 3.0.3 on 2020-04-09 18:51

from django.db import migrations


def add_about_info(apps, schema_editor):
    Information = apps.get_model('contact', 'Information')
    Information.objects.create(title='about', detail='')


def add_remove_info(apps, schema_editor):
    Information = apps.get_model('contact', 'Information')
    Information.objects.get(title='about').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_about_info, add_remove_info),
    ]
