# Generated by Django 3.0.3 on 2020-03-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Gender Male'), (2, 'Gender Female'), (3, 'Gender Other')], null=True),
        ),
    ]
